cluster-autoscaler.spec, images/cluster-autoscaler/Dockerfile
=> Add rpm spec file and dockerfile for cluster autoscaler.

cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
Switch from labels to annotations for min and max sizes values.
=> UPSTREAM: <carry>: cluster-api switch to annotations

cluster-autoscaler/cloudprovider/aws/aws_manager.go
Backporting https://github.com/kubernetes/autoscaler/pull/1425
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1631635
=> UPSTREAM :1425: Report unknown AWS EC2 instance types requested by ASGs

cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go, cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
Remove unused fields in types nodegroup and provider.
=> UPSTREAM: <carry>: openshiftmachineapi: remove unused fields

cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
=> UPSTREAM: <carry>: openshift: remove TODO

cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
This reworks `TestNodeGroup{Increase,Decrease}Size()` to use subtests.
The change is to ensure we are testing both MachineSets and
MachineDeployments in all cases we construct a nodegroup.
By switching to subtests it is easier to see those places where
machine deployments are not being tested as the the output for each
test function should show that MachineDeployment and MachineSet is
listed in the test name output.
```console
--- PASS: TestNodeGroupIncreaseSize (0.61s)
--- PASS: TestNodeGroupIncreaseSize/MachineSet (0.30s)
--- PASS: TestNodeGroupIncreaseSize/MachineSet/errors_because_delta_is_negative (0.10s)
--- PASS: TestNodeGroupIncreaseSize/MachineSet/errors_because_initial+delta_>_maxSize (0.10s)
--- PASS: TestNodeGroupIncreaseSize/MachineSet/no_error_as_within_bounds (0.10s)
--- …
```
=> UPSTREAM: <carry>: openshift: Rework TestNodeGroupResize

cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
This reworks TestControllerNodeGroups to use subtests. The change is
to ensure we are testing both MachineSets and MachineDeployments in
all cases we construct a nodegroup.
By switching to subtests it is easier to see those places where
machine deployments are not being tested as the the output for each
test function should show that MachineDeployment and MachineSet is
listed in the test name output.
```console
--- PASS: TestControllerNodeGroups (0.61s)
--- PASS: TestControllerNodeGroups/MachineSet (0.30s)
--- PASS: TestControllerNodeGroups/MachineSet/errors_with_bad_annotations (0.10s)
--- PASS: TestControllerNodeGroups/MachineSet/success_with_zero_bounds (0.10s)
--- PASS: TestControllerNodeGroups/MachineSet/success_with_positive_bounds (0.10s)
--- PASS: …
```
=> UPSTREAM: <carry>: openshift: Rework TestControllerNodeGroups

cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
Simplify test setup using `newMachineController()`.
=> UPSTREAM: <carry>: openshift: Rework TestControllerFindMachineByID

hack/verify_history.sh
Tested on https://github.com/openshift/kubernetes-autoscaler/pull/71
/assign @frobware
=> UPSTREAM: <carry>: openshift: create git history verification script

Makefile, cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go, hack/go-fmt.sh, hack/go-lint.sh, hack/go-vet.sh
=> UPSTREAM: <carry>: openshift: Add fmt, lint, vet scripts/Makefile

test/openshift/Gopkg.lock, test/openshift/vendor/github.com/openshift/api/config/v1/types_cluster_operator.go, test/openshift/vendor/github.com/openshift/api/config/v1/types_cluster_version.go, test/openshift/vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go, test/openshift/vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.lock, test/openshift/vendor/github.com/openshift/cluster-api-actuator-pkg/Gopkg.toml, test/openshift/vendor/github.com/openshift/cluster-api-actuator-pkg/Makefile, test/openshift/vendor/github.com/openshift/cluster-api-actuator-pkg/hack/ci-integration.sh, test/openshift/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/autoscaler/autoscaler.go, test/openshift/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/clusterapi.go, test/openshift/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/framework/clusters.go, test/openshift/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/infra/infra.go, test/openshift/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/e2e/operators/utils.go, test/openshift/vendor/github.com/openshift/cluster-api-actuator-pkg/pkg/manifests/manifests.go
Pick up openshift/cluster-api-actuator-pkg#78
=> UPSTREAM: <carry>: openshift: vendor github.com/openshift/cluster-api-actuator-pkg

vertical-pod-autoscaler/Dockerfile.openshift, vertical-pod-autoscaler/Dockerfile.rhel7
Here's my version of #94 
@sjenning @derekwaynecarr 
I'll open a PR against release for the build configs and jobs and reference this PR
=> Add OpenShift VPA image builds

cluster-autoscaler.spec, hack/go-fmt.sh, hack/go-lint.sh, hack/go-vet.sh, images/cluster-autoscaler/Dockerfile, images/cluster-autoscaler/Dockerfile.rhel7
Switch cluster-autoscaler builds to Go 1.12.
=> UPSTREAM: <carry>: openshift: Switch builds to use Go 1.12

cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
This reworks the logic in DeleteNodes([]nodes) to:
- annotate a node for deletion
- drop the replica count by 1 immediately
- fail fast on any error during those steps
This is different from the current behaviour which first annotated all
the nodes then dropped the replica count by len(nodes). The goal here
is to not leave machines and the respective machine set replica count
in an indeterminate state should any error occur.
=> UPSTREAM: <carry>: openshift: Rework logic in DeleteNodes()

cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go, cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
This change adds detection for an environment variable to specify the
version and group for the clusterapi resources. If the environment
variable `MACHINEAPI_VERSION_GROUP` is specified, then it will
be used instead of the default. This change also adds new tests to
exercise the functionality.
associated issue: https://issues.redhat.com/browse/OCPCLOUD-808
=> UPSTREAM: <carry>: openshift: add the ability to specify clusterapi gvr in env

OWNERS
So that I can approve and that I get assigned PRs to review
=> Add JoelSpeed to Owners

hack/verify_history.sh
Problems with old version:
* only looked at the top commit
* always assumed merges to master branch
* used upper-case shell variables
* didn't handle PR numbers for upstream
* required extraneous "openshift: " in commit messages
* provided no feedback on what messages should look like
=> Fix git commit message verification script

OWNERS, cluster-autoscaler/OWNERS
Removing myself from the OWNERS file.
=> Remove bison from OWNERS file

cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_machinedeployment.go, cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_machineset.go, cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
=> [release-4.4] BUG 1835160: Fallback to status if replicas nil in spec

OWNERS
these entries inform the openshift bugzilla tooling about the
categories of this project.
=> add component and subcomponent to OWNERS

images/cluster-autoscaler/Dockerfile.rhel
=> Fix build with Go 1.16

.snyk
Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!
=> OCPBUGS-25625: Add Snyk file to exclude vendor directory on scan

.snyk
Hello! This is a PR to add a snyk file to exclude the vendors folder while scanning the repo. Thanks!
=> OCPBUGS-23576: Add Snyk file to exclude vendor directory on scan

cluster-autoscaler/core/static_autoscaler.go
this is a carry of the upstream 7954 PR.
=> OCPBUGS-54231: Fix cool down status condition to trigger scale down

cluster-autoscaler/core/static_autoscaler.go
this is a backport of the upstream PR 7954.
=> [release-4.16] OCPBUGS-59267: Fix cool down status condition to trigger scale down
