openshift/kubernetes-autoscaler

- cluster-autoscaler.spec
Fixes: https://jira.coreos.com/browse/ART-242
> cluster-autoscaler.spec: bump golang_version to 1.10.4

- cluster-autoscaler.spec
Second pass at fixing this: https://jira.coreos.com/browse/ART-244
> cluster-autoscaler.spec: set golang_version to 1.10

- cluster-autoscaler/cloudprovider/gke/autoscaling_gke_client_v1beta1_test.go
This is the same change as was done in
https://github.com/kubernetes/autoscaler/pull/1356 where I see
intermittent CI failures on AWS CI instances.
Signed-off-by: Andrew McDermott <amcdermo@redhat.com>
> UPSTREAM: <carry>: gce: increase test timeout in TestWaitForGkeOp

- cluster-autoscaler/core/scale_down.go
Explicitly handle nil as a return value for nodeGroup in
`calculateScaleDownGpusTotal()` when `NodeGroupForNode()` is called
for GPU nodes that don't exist. The current logic generates a runtime
exception:
"reflect: call of reflect.Value.IsNil on zero Value"
Looking through the rest of the tree all the other places that use
this pattern additionally and explicitly check whether `nodeGroup ==
nil` first.
This change now completes the pattern in
`calculateScaleDownGpusTotal()`.
Looking at the other occurrences of this pattern we see:
```
File: clusterstate/clusterstate.go
488:26:		if nodeGroup == nil || reflect.ValueOf(nodeGroup).IsNil() {
File: core/utils.go
231:26:		if nodeGroup == nil || reflect.ValueOf(nodeGroup).IsNil() {
322:26:		if nodeGroup == nil || …
```
> UPSTREAM: <carry>: handle nil nodeGroup in calculateScaleDownGpusTotal

- cluster-autoscaler/core/scale_up.go
When scaling up, the calculation for the maximum size of the cluster
based on `--max-nodes-total` doesn't take into account any nodes that
are in the process of coming up. This allows the cluster to grow
beyond the size specified.
With this change I now see:
scale_up.go:266] 21 other pods are also unschedulable
scale_up.go:423] Best option to resize: openshift-cluster-api/amcdermo-ca-worker-us-east-2b
scale_up.go:427] Estimated 18 nodes needed in openshift-cluster-api/amcdermo-ca-worker-us-east-2b
scale_up.go:432] Capping size to max cluster total size (23)
static_autoscaler.go:275] Failed to scale up: max node total count already reached
> UPSTREAM: <carry>: fix calculation of max cluster size

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
- cluster-autoscaler/cloudprovider/clusterapi/export_test.go
This PR adds unit tests for the utility functions in clusterapi/clusterapi_utils.go.
I've chosen to take a black box testing approach and exported those functions that we consider to be "public" by exporting the functionality even though they are all private to the clusterapi implementation.
> UPSTREAM: <carry>: cluster-api: add unit tests for utility functions

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
Upstream uses "cluster.k8s.io/machine" as do all the current openshift
actuators (libvirt & AWS) as does the nodelink controller.
> UPSTREAM: <carry>: cluster-api: remove obsolete usage of "machine" annotation

- OWNERS
Same as #27. Recreated so we can merge it without failing e2e test.
Assign file ownership to cloud team
CC: @frobware @ingvagabund
> assign ownership to cloud team

- cluster-autoscaler/cloudprovider/aws/aws_manager.go
When requesting for aws asg it may happen the launch configuration
name is not set (set to nil pointer). Causing the cluster autoscaler
to panic when accesing the nil pointer.
One line change picked from https://github.com/kubernetes/autoscaler/pull/867.
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1631635
> UPSTREAM: <carry> Return error if launch configuration name is missing

- test/openshift/e2e/operator_expectations.go
Reworked the e2e test to delete the workload. This will:
- delete all workload-based pods
- the autoscaler will notice that there are nodes without any utilisation 
- the autoscaler will scale down
The smoke tests asserts that:
- the MachineSet's replicas drops to its original number.
- the number of nodes in the cluster drops to the original count before scale up
I also reduced the number of replicas we spin up from 12 => 2 as we're only testing for a delta of 1.
> test/openshift/e2e: Smoke test for scale down

- test/openshift/e2e/main.go
As we have now pivoted to machine.openshift.io/v1beta1 this changes the namespace when running the tests to `openshift-machine-api` for consistency.
> UPSTREAM: <carry>: test/openshift/e2e: switch namespace to openshift-machine-api

- test/openshift/Gopkg.lock
- test/openshift/e2e/main.go
- test/openshift/e2e/operator_expectations.go
- test/openshift/vendor/sigs.k8s.io/controller-runtime/pkg/runtime/signals/doc.go
- test/openshift/vendor/sigs.k8s.io/controller-runtime/pkg/runtime/signals/signal.go
- test/openshift/vendor/sigs.k8s.io/controller-runtime/pkg/runtime/signals/signal_posix.go
- test/openshift/vendor/sigs.k8s.io/controller-runtime/pkg/runtime/signals/signal_windows.go
Setup a signal handler in main and also pass a `context.Context` to the `Expect...()` functions. The signal handler will cancel the context and the expect functions can now be notified of the interruption (or cancellation) and run any subsequent cleanup operations.
The `ExpectAutoscalerScalesOut()` test now deletes the following objects on either successful completion of the test or when a `SIGINT` or `SIGTERM` is received:
- workload object (if still present)
- clusterautoscalers
- machineautoscalers
The is particularly handy when running the e2e tests manually as you no longer have to clean up the objects that are created before invoking the test again.
> UPSTREAM: <carry>: test/openshift/e2e: handle SIGINT and SIGTERM

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
This value is printed a lot during normal execution and it is really
for debug only so logging at level 4.
> UPSTREAM: <carry>: openshift: log nodegroup discovery at level 4

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
- Validate nodes passed to nodegroup.DeleteNodes() are actually from the same node group.
- Add unit tests to verify the behaviour
Built on top of PR #34
> UPSTREAM: <carry>: openshift: validate nodegroup membership in DeleteNodes()

- cluster-autoscaler/core/scale_up.go
When scaling up the calculation for computing the maximum cluster size
does not take into account the number of any upcoming nodes and it is
possible to grow the cluster beyond the cluster
size (--max-nodes-total).
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1670695
> UPSTREAM: <carry>: fix max cluster size calculation on scale up

- test/openshift/Makefile
This target is to help those developing the autoscaler cloud provider.
It focuses on autoscaler tests only.
- For all ginkgo e2e tests it also sets `-ginkgo.noColor=true` which
can help when parsing logs from the CLI.
> UPSTREAM: <carry>: test/openshift/e2e: add Autoscaler focused target

- cluster-autoscaler/core/static_autoscaler.go
Print the correct error variable if a scale down error occurs.
Previously this was printing `err` which was a) not the correct
variable and b) would always have the value `<nil>`.
> UPSTREAM: <carry>: openshift: cluster-autoscaler/core: print correct error

- test/openshift/Makefile
Ensure dep(1) is available before running it.
> UPSTREAM: <carry>: test/openshift: go get dep if it doesn't exist

- test/openshift/Makefile
Add a makefile target `revendor-test-e2e` that captures the runes to bump the e2e test dependencies.
> UPSTREAM: <carry>: test/openshift/Makefile: add rule to bump deps

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
This is the beginning of a sequence of commits to change the test functions in nodegroup to use subtests. The intent is to ensure we are testing both MachineSets and MachineDeployments in all cases we construct a nodegroup.
By switching to subtests it will become easier to see those places where machine deployments are not being tested as the the output for each test function should show that `MachineDeployment` and `MachineSet` is listed in the test name output.
```console
--- PASS: TestNodeGroupNewNodeGroup (0.00s)
--- PASS: TestNodeGroupNewNodeGroup/MachineDeployment (0.00s)
--- PASS: TestNodeGroupNewNodeGroup/MachineDeployment/errors_because_minSize_is_invalid (0.10s)
--- PASS: TestNodeGroupNewNodeGroup/MachineDeployment/errors_because_maxSize_is_invalid (0.11s)
--- PASS: …
```
> UPSTREAM: <carry>: openshift: Rework TestNodeGroupNewNodeGroup

- cluster-autoscaler/cloudprovider/aws/aws_manager.go
- cluster-autoscaler/cloudprovider/aws/aws_manager_test.go
Replicated changes from kubernetes "Add AWS Custom Endpoint capability #70588" into cluster-autoscaler:
- Modified aws_manager snd aws_manager_test similar to kubernetes aws and aws_test.
> UPSTREAM: 1745: Allow custom AWS region overrides

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_utils_test.go
Switch to using subtests vis-a-vis using t.Logf() to identify the test
being run.
> UPSTREAM: <carry>: openshift: Rework utils test funcs

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
This reworks `TestNodeGroupMachineSetDeleteNodes` to use subtests. The
change is to ensure we are testing both MachineSets and
MachineDeployments in all cases we construct a nodegroup.
By switching to subtests it is easier to see those places where
machine deployments are not being tested as the the output for each
test function should show that MachineDeployment and MachineSet is
listed in the test name output.
```console
--- PASS: TestNodeGroupDeleteNodes (0.20s)
--- PASS: TestNodeGroupDeleteNodes/MachineSet (0.10s)
--- PASS: TestNodeGroupDeleteNodes/MachineDeployment (0.10s)
```
> UPSTREAM: <carry>: openshift: Rework TestNodeGroupDeleteNodes

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
This reworks TestControllerNodeGroupForNodeLookup to use subtests. The
change is to ensure we are testing both MachineSets and
MachineDeployments in all cases we construct a nodegroup.
By switching to subtests it is easier to see those places where
machine deployments are not being tested as the the output for each
test function should show that MachineDeployment and MachineSet is
listed in the test name output.
```console
--- PASS: TestControllerNodeGroupForNodeLookup (0.61s)
--- PASS: TestControllerNodeGroupForNodeLookup/MachineSet (0.30s)
--- PASS: TestControllerNodeGroupForNodeLookup/MachineSet/lookup_is_nil_because_no_annotations (0.10s)
--- PASS: TestControllerNodeGroupForNodeLookup/MachineSet/lookup_is_nil_because_scaling_range_==_0 (0.10s)
--- PASS: …
```
> UPSTREAM: <carry>: openshift: Rework TestControllerNodeGroupForNodeLookup

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
Check for explicit error mesages in TestNodeGroupIncreaseSize() and
TestNodeGroupDecreaseSize(). These functions now only test the
expected error cases on bad inputs. A follow-up PR will test for the
success case which needs additional test setup code.
> UPSTREAM: <carry>: openshift: check for explicit errors

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
Add explicit unit tests for:
- nodegroup.IncreaseSize()
- nodegroup.DecreaseTargetSize()
This is a follow-up to https://github.com/openshift/kubernetes-autoscaler/pull/68.
> UPSTREAM: <carry>: openshift add unit tests to resize nodegroup

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider_test.go
This a rework of how the unit tests setup the controller and the objects under test. We previously accumulated three ways of setting up the tests - this change reduces that to using just one way, providing uniformity and consistency for all the tests.
The controller functions now return the `nodegroup` type rather than `cloudprovider.<type>` to make unit testing easier. The upper layers (i.e., the provider) convert the `nodegroup` to `cloudprovider.NodeGroup`. A `nodegroup` is a `cloudprovider.NodeGroup` so the overall change here is really small - it only changes the function signature.
Plus various drive-by fixes in the unit tests themselves to:
- remove unused fields
- fix-up some nil-pointer analysis highlighted by latest GoLand 2019.1 release
- increases the existing tests to also …
> UPSTREAM: <carry>: openshift: clean up test setup

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
This disables the use and discovery of MachineDeployment's as a
resource that can be scaled. As OpenShift 4.1 does not deploy the
MachineDeployment CRD we explicitly disable trying to discover that
resource type in normal operation; the unit tests continue to test
with both MachineSet's and MachineDeployment's.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1700701.
> UPSTREAM: <carry>: openshift: disable MachineDeployment in normal operation

- cluster-autoscaler/core/static_autoscaler.go
This enables the e2e autoscaler tests [1] to verify that, when specified, `--max-nodes-total` is not exceeded when scaling out.
[1] openshift/cluster-api-actuator-pkg#77
> UPSTREAM: <carry>: openshift: record max-nodes-total event

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
`BuildConfigFromFlags()` will handle `--kubeconfig` path if it is set,
otherwise it will use the in-cluster config.
> UPSTREAM: <carry>: openshift: simplify config creation

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
Change findMachineByNodeProviderID() to first match using ProviderID value. If there is no match (because actuator does not set the value on the machine object) then fallback to matching based on the "machine" annotation from the node object (should it exist). By falling back to the "machine" annotation on the node object we don't break compatibility with the behaviour in OpenShift 4.1.0.
> UPSTREAM: <carry>: openshift: prioritise search by Provider ID

- cluster-autoscaler/core/scale_up.go
- cluster-autoscaler/core/static_autoscaler.go
This moves the location of where the event is emitted from by reverting PR #90 and emitting the event during scale-up.
> UPSTREAM: <carry>: openshift: Move MaxNodesTotalReached event

- cluster-autoscaler/core/scale_up.go
Be less specific as to when the event is generated. The qualifying
criteria occurs when adding a node would reach the --max-nodes-total
specified.
> UPSTREAM: <carry>: openshift: move MaxNodesTotalReached event again

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
When creating a test config I had previously allowed for the number of
nodes to be different to the number of replicas. We don't use this
distinction so dropping that entirely from all the unit tests.
> UPSTREAM: <carry>: openshift: simplify test setup for nodes/replicas

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
We previously only considered a MachineSet or MachineDeployment
suitable for scaling if it had positive scaling bounds.
For example:
annotations:
machine.openshift.io/cluster-api-autoscaler-node-group-min-size: "1"
machine.openshift.io/cluster-api-autoscaler-node-group-max-size: "6"
On us-west-2 we have:
$ kubectl get machinesets
NAME                                  DESIRED   CURRENT   READY   AVAILABLE   AGE
amcdermo-ca-5ws2b-worker-us-west-2a   1         1         1       1           4h23m
amcdermo-ca-5ws2b-worker-us-west-2b   1         1         1       1           4h23m
amcdermo-ca-5ws2b-worker-us-west-2c   1         1         1       1           4h23m
amcdermo-ca-5ws2b-worker-us-west-2d   0         0                             4h23m
but the autoscaler will fail to scale up any of …
> UPSTREAM: <carry>: openshift: update criteria for returning a nodegroup

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider_test.go
This is largely to be consistent with other usages (in the community)
but really to be at parity with the upstream PR [1] that uses this
import alias already. This also makes it easier to backport changes
made from openshift/autoscaler into upstream.
[1] https://github.com/kubernetes/autoscaler/pull/1866
> UPSTREAM: <carry>: openshift: reference k8s.io/api/core/v1 as corev1

- cluster-autoscaler/core/scale_up.go
The original intent of the event was to convey that the ceiling had
been reached. This now logs that configured maximum.
> UPSTREAM: <carry>: openshift: report MaxNodesTotal count

- cluster-autoscaler/main.go
- cluster-autoscaler/processors/nodegroupset/openshiftmachineapi_compare_nodegroups.go
In OpenShift clusters we see very small memory differences between
instances, typically 8Ki. The default comparator which is used when
--balance-similar-node-groups is enabled only considers nodes in a
nodegroup to be equal when the memory capacity is identical. This new
comparator is identical to the default but will tolerate a 128Ki
difference in memory capacity.
With this change, and with --balance-similar-node-groups enabled, I
now see the following:
```console
$ oc get machinesets
NAME                               DESIRED   CURRENT   READY   AVAILABLE   AGE
amcdermo-w6m6z-worker-us-east-2a   3         3         3       3           24h
amcdermo-w6m6z-worker-us-east-2b   4         4         4       4           24h
amcdermo-w6m6z-worker-us-east-2c   4         4         4       4 …
```
> UPSTREAM: <carry>: openshift: add custom nodeset comparator

- Makefile
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider_test.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_utils_test.go
- hack/goimports.sh
So the target can be run in CI and fail in case files are not properly goimport formated.
> UPSTREAM: <carry>: openshift: Extend makefile with 'make goimports' target

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_machinedeployment.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_machineset.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_scalableresource.go
The autoscaler expects provider implementations nodeGroups to implement the Nodes() function to return the number of instances belonging to the group regardless of they have become a kubernetes node or not.
This information is then used for instance to realise about unregistered nodes https://github.com/kubernetes/autoscaler/blob/bf3a9fb52e3214dff0bea5ef2b97f17ad00a7702/cluster-autoscaler/clusterstate/clusterstate.go#L307-L311
Related https://github.com/kubernetes/autoscaler/pull/2815
> Bug 1801254: UPSTREAM: <carry>: openshift: Let Nodes() return the list of all machines

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
Without this, the autoscaler where using the labels in `compareLabels` and failing to match similar groups in different zones. Starting in kube 1.17 `failure-domain.beta.kubernetes.io/*` are deprecated in favour of `topology.kubernetes.io/*` https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#failure-domainbetakubernetesiozone
https://github.com/kubernetes/autoscaler/pull/2848
> BUG 1803639: UPSTREAM: <carry>: openshift: Add topology.kubernetes.io labels to be ignored when comparing similar node groups

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_nodegroup_test.go
I have seen the autoscaler call `DeleteNodes` several times while a node it is trying to delete has not been fully deleted (finalizer still present). Currently, it does not check if the node's Machine has already been deleted and blindly reduces the size of the node group by 1 on every call to `DeleteNodes`
This PR adds a check, so that if a node's `Machine` already has a deletion timestamp, we do not decrease the size of the node group any further
I've added a test that calls the `DeleteNodes` twice and expects the node group size to not decrease on the second call, which passes with the fix, and fails without
> BUG 1804738: Ensure DeleteNodes doesn't delete a node twice

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider_test.go
This was missed in the review of https://github.com/openshift/kubernetes-autoscaler/pull/130
> UPSTREAM: <carry>: openshift: enable machineapi_provider_test

- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_controller_test.go
- cluster-autoscaler/cloudprovider/openshiftmachineapi/machineapi_provider.go
Decouples the API group from the version and let the latter to be discovered dynamically.
Needs https://github.com/openshift/kubernetes-autoscaler/pull/133
> Discover api version

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_converters.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_converters_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
This allows a Machine{Set,Deployment} to scale up/down from 0,
providing the following annotations are set:
```yaml
apiVersion: v1
items:
- apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
annotations:
machine.openshift.io/cluster-api-autoscaler-node-group-min-size: "0"
machine.openshift.io/cluster-api-autoscaler-node-group-max-size: "6"
machine.openshift.io/vCPU: "2"
machine.openshift.io/memoryMb: 8G
machine.openshift.io/GPU: "1"
machine.openshift.io/maxPods: "100"
```
please note that `machine.openshift.io/maxPods` is not required for scale to/from zero operations.
this PR is a continuation of the work started in #110 
Counterpart PRs:
openshift/cluster-api-provider-aws#301
openshift/cluster-api-provider-azure#112
Design details:
openshift/enhancements#186
> UPSTREAM: <carry>: openshift: Implement scale from zero

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
When https://github.com/kubernetes/autoscaler/pull/1866 introduced the CAPI provider, all Provider IDs from nodes were being normalized so that internally, there were no differences (eg some places using normalized, some not)
However, the clusterstateregistry and anything outside of the CPAI provider does not expect the instance IDs to be normalized, and so nodes were being marked as unregistered due to the normalized ID not matching the non-normalized ID coming from the Nodes on the cluster.
This PR makes it so that Instance IDs fetched and passed externally are not normalized, fixing the unregistered node logic in the clusterstateregistry when using the CAPI provider.
/cc @enxebre @elmiko 
Upstream: https://github.com/kubernetes/autoscaler/pull/3057
> UPSTREAM: 3057: openshift: Do not normalize Node IDs outside of CAPI provider

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_converters.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_converters_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/machinedeployment_types.go
- cluster-autoscaler/cloudprovider/clusterapi/machineset_types.go
Since we don't have defaulting for MachineSets, we can get into a scenario where the replicas field is nil. Currently the behaviour for dereferencing the replicas returns 0 if the replicas field is nil. This prevents scaling operations at present.
This PR adds a fallback mechanism which uses the `status.replicas` field instead if the `spec.replicas` field is not present. This should allow the autoscaler to continue working
> BUG 1820654: UPSTREAM: <carry>: openshift: Fallback to status if replicas nil in spec

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
This change adds two different checks for improving the behavior of node
deletion. The first is to check against the node group minimum size
instead of zero for determining early scale down failure events. The
second is to help prevent race conditions in the annotation labeling for
machines marked for deletion.
> BUG 1820410: UPSTREAM: 3034: openshift: Improve delete node mechanisms

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
For autoscaling from zero, the autoscaler should convert the mem value received in the appropriate annotation to bytes using powers of two consistently with other providers and fail if the format received is not expected. This gives robust behaviour consistent with cloud providers APIs and providers implementations.
https://cloud.google.com/compute/all-pricing
https://www.iec.ch/si/binary.htm
https://github.com/openshift/kubernetes-autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/aws_manager.go#L366
> Bug 1828731: UPSTREAM: <carry>: Convert the mem value consistently with other providers

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
Allow instances to have up to a 256KB delta in actual memory capacity
This commit was introduced into master during the 4.4 release cycle as part of #121
> BUG 1824215: Raise maximum memory capacity difference

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
When getting Replicas() the local struct in the scalable resource might be stale. To mitigate possible side effects, we want always get a fresh replicas.
This is one in a series of PR to mitigate https://github.com/kubernetes/autoscaler/issues/3104
Once we got all of them merged we'll put a PR upstream.
> Bug 1823667: UPSTREAM: <carry>: Get replicas always from API server

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
When calling deleteNodes() we should fail early if the operation could delete nodes below the nodeGroup minSize().
This is one in a series of PR to mitigate kubernetes#3104
Once we got all of them merged we'll put a PR upstream.
> Bug 1823667: UPSTREAM: <carry>: Compare against minSize in deleteNodes()

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
The test was relying on the `TargetSize` to determine if the nodes had been deleted twice. Until #147 was merged, this value would have been the original value from when the nodegroup was constructed and did not reflect the true size of the MachineSet/Deployment underlying the nodegroup
I've updated the test to:
- Check that the client sees the deletion timestamp added to Machines
- Wait for the Nodegroup to have the correct number of replicas after the first iteration
- Check against the API for the final check of the replica count so that we don't rely on our own implementation to pass the test
> Bug 1835851: Update DeleteNodesTwice test

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
This change adds a mutex to the MachineController structure which is
used to gate access to the DeleteNodes function.
This is one in a series of PRs to mitigate kubernetes#3104
> Bug 1823667: UPSTREAM: <carry>: Add mutex to DeleteNodes

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machinedeployment.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_scalableresource.go
This change removes a few nil checks against resources returned in the
Mark and Unmark deletion functions of the cluster-autoscaler CAPI
provider. These checks look to see if the returned value for a resource
are nil, but the function will not return nil if it returns an
error[0]. We only need to check the error return as discussed here[1].
[0]
https://github.com/kubernetes/client-go/blob/master/dynamic/simple.go#L234
[1]
https://github.com/openshift/kubernetes-autoscaler/pull/141/files#r414480960
> UPSTREAM: <carry>: remove redundant error checks in mark/unmark deletion functions

- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/static_autoscaler.go
- cluster-autoscaler/utils/deletetaint/delete.go
Bug fix for  : https://bugzilla.redhat.com/show_bug.cgi?id=1843039
Backport request from https://github.com/kubernetes/autoscaler/pull/830
> Bug 1843039: Add support for rescheduled pods with the same name in drain

- cluster-autoscaler/processors/nodegroupset/compare_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/compare_nodegroups_test.go
This allows a small tolerance in the memory capacity of nodes to allow better matching of similar node groups. There are differences in the memory values that Kubernetes interprets due to variances in the instances that a cloud provider provides.
Also adds tests that match real values from a real set of nodes that would be expected to be the same (the same instance type across multiple availability zones within a given region)
Eg. In testing I saw AWS m5.xlarge nodes with capacities such as `16116152Ki` and `15944120Ki` not only across availability zones, but within the same availability zone after a few cycles through machines. This is a difference on `168Mi` which is much larger than the original tolerance of 128000 Bytes which was preventing `BalanceSimilarNodeGroups` from balancing …
> BUG 1824215: Allow small tolerance on memory capacity when comparing nodegroups

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
If a nodegroup cannot scale from zero, and the replicas count is `nil`, then the nodegroup will be ignored by the autoscaler and won't be scaled. We implemented #143 to prevent allow the autoscaler to continue operating when replicas is `nil`, but it only works for nodegroups that can scale from zero presently.
> Bug 1852061: Fallback to Status Replicas if Replicas nil when listing NodeGroups

- vertical-pod-autoscaler/Dockerfile.rhel
This change adds a new Dockerfile.rhel file to control building release
images. It updates the baseimages in the Dockerfile used for promotion
in order to ensure it matches the configuration in the
[ocp-build-data
repository](https://github.com/openshift/ocp-build-data/tree/openshift-4.6-rhel-8/images)
used for producing release artifacts.
After this change merges, the release files in
https://github.com/openshift/release/blob/master/ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master.yaml
and
https://github.com/openshift/ocp-build-data/blob/openshift-4.6/images/vertical-pod-autoscaler.yml
should be updated with the new dockerfile path.
> BUG 1872080: Add vertical-pod-autoscaler/Dockerfile.rhel to match build configuration in ocp-build-data

- images/cluster-autoscaler/Dockerfile.rhel
This change adds a new Dockerfile.rhel file to control building release
images. It updates the baseimages in the Dockerfile used for promotion
in order to ensure it matches the configuration in the
[ocp-build-data repository](https://github.com/openshift/ocp-build-data/tree/openshift-4.6-rhel-8/images)
used for producing release artifacts.
After this change merges, the release files in
https://github.com/openshift/release/blob/master/ci-operator/config/openshift/kubernetes-autoscaler/openshift-kubernetes-autoscaler-master.yaml
and
https://github.com/openshift/ocp-build-data/blob/openshift-4.6/images/atomic-openshift-cluster-autoscaler.yml
should be updated with the new dockerfile path.
> Bug 1872080: Add images/cluster-autoscaler/Dockerfile.rhel to match build configuration in ocp-build-data

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_converters.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_machineset.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
This should resolve issues where nodegroups are scaling from zero and need to schedule pods based on some well known labels that are applied to nodes.
We have discovered that if there are no healthy nodes within a node group (eg they are all cordoned) then this also counts as scaling from zero in the eyes of the autoscaler, so there is actually a chance we can copy labels from a node that exists, hence this has also been added.
There are a few options we could consider in this solution:
- Copying all labels from the existing node and not using the machinset/generic labels in that case
- Having the nodegroup store a copy of valid node labels from a node that it has seen in the past to improve the scale from zero experience when there genuinely are no nodes available to get labels from
I …
> Bug 1891551: Ensure the node template include up to date and informative labels

- cluster-autoscaler/cloudprovider/clusterapi/README.md
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_autodiscovery.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_autodiscovery_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
This change set brings in the upstream pull request (https://github.com/kubernetes/autoscaler/pull/3314) to add an option for node group autodiscovery. It also carries a patch to ensure that the changes to do not disrupt openshift.
> Add upstream patch for node group autodiscovery

- cluster-autoscaler/cloudprovider/clusterapi/README.md
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
this pr brings in the patch for update group identifiers, see https://github.com/kubernetes/autoscaler/pull/3161
> Bug 1906933: Add upstream patch for update group identifier

- OWNERS
We don't have an owners file on this branch, and we should do, add current team members as owners so that we can all approve PRs to this branch
> [release-3.11] Add owners file for current cluster infrastructure team

- vertical-pod-autoscaler/pkg/admission-controller/config.go
When switching the VPA admission controller to the v1 admissionregistration API,
the FailurePolicy was changed from Ignore to Fail.
Using Fail makes pod creation depend on VPA and can cause a deadlock when the
admission controller pod itself can't be scheduled again.
See https://github.com/kubernetes/autoscaler/pull/3456
> Bug 1927854: VPA: Ignore admission hook failures

- hack/go-fmt.sh
- hack/go-lint.sh
- hack/go-vet.sh
- hack/goimports.sh
Some of our tests (eg vet) are failing due to the age of the golang
version that is used for the containers. This change updates the version
to 1.16.
> Bug 1955324: update testing scripts to use go 1.16

- cluster-autoscaler/version/version.go
this commit was late in landing upstream, adding it now to make sure we have the proper version in the binary
> Bug 1948719: updating CA version to 1.21.0

- images/cluster-autoscaler/Dockerfile
- images/cluster-autoscaler/Dockerfile.rhel
This change adds build tags to the dockerfiles for the cluster
autoscaler. This tag will restrict the binary to only contain the
clusterapi provider.
Additionally, the community facing dockerfile has been updated to build
from public/ubi sources, go lang 1.16, and more closely matches the rhel
version.
*NOTE* this commit should be squashed into the primary OpenShift commit
that configures the repository, ref:
c681f96ed154f698bce4546b07fe8e9ce1ea7196
> Bug 1991496: add clusterapi build tags to dockerfiles

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
This is to ensure the CAPI provider has the upstream CAPI annotations so it can be used with CAPI in hypershift.
In a future rebase this commit can be conflated with https://github.com/openshift/kubernetes-autoscaler/commit/20e2e2648595e529e6c9ff5637d3f05a860234cf.
> UPSTREAM: <carry>: Fallback to CAPI annotations

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
Because the autoscaler assumes it can delete nodes in parallel, it
fetches nodegroups for each node in separate go routines and then
instructs each nodegroup to delete a single node.
Because we don't share the nodegroup across go routines, the cached
replica count in the scalableresource can become stale and as such, if
the autoscaler attempts to scale down multiple nodes at a time, the
cluster api provider only actually removes a single node.
To prevent this, we must ensure we have a fresh replica count for every
scale down attempt.
> Bug 2043675: UPSTREAM: <drop>: Ensure ClusterAPI DeleteNodes accounts for out of band changes scale

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
During the most recent rebase of the autoscaler, this constant was
overwritten. This patch is being added to revert the original state of
the constant.
TODO: during the next rebase of the autoscaler, this commit should be
dropped in favor of taking the upstream constant directly. This may
involve modifying a previous carry commit to include the upstream
value.
> Bug 2045561: revert defaultCAPIGroup constant

- cluster-autoscaler/cloudprovider/clusterapi/README.md
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
This change introduces an environment variable, `CAPI_VERSION`, through
which a user can set the API version for the group they are using. This
change is being added to address situations where a user might have
multiple API versions for the cluster api group and wishes to be
explicit about which version is selected.
Also adds unit tests and documentation for the new behavior. This change
does not break the existing behavior.
> add user configurable cluster api version

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
This is to ensure the CAPI provider has the upstream CAPI annotations so it can be used with CAPI in hypershift.
cherry-picks https://github.com/openshift/kubernetes-autoscaler/pull/214
Fixes #
```release-note
```
```docs
```
> Bug 2066270: UPSTREAM: <carry>: Fallback to CAPI annotations

- vertical-pod-autoscaler/pkg/recommender/input/cluster_feeder.go
Since prometheus adapter returns metrics for a phantom container named "POD" for every pod which has an init container, the VPA recommender should ignore the missing metrics for any such "POD" container.
vertical-pod-autoscaler
> Bug 1944065: Have VPA ignore phantom containers named "POD"

- cluster-autoscaler/processors/nodegroupset/clusterapi_nodegroups.go
- cluster-autoscaler/processors/nodegroupset/clusterapi_nodegroups_test.go
this change adds labels that are used on Alibaba Cloud and IBM Cloud for
CSI and CCM.
> Bug 2001027: update clusterapi nodegroups processor

- cluster-autoscaler/core/scale_down.go
- cluster-autoscaler/core/scale_down_test.go
- cluster-autoscaler/core/static_autoscaler_test.go
- cluster-autoscaler/simulator/cluster.go
- cluster-autoscaler/simulator/cluster_test.go
- cluster-autoscaler/simulator/drain.go
- cluster-autoscaler/simulator/drain_test.go
- cluster-autoscaler/utils/drain/drain.go
- cluster-autoscaler/utils/drain/drain_test.go
- cluster-autoscaler/utils/kubernetes/listers.go
this patch is being carried on the openshift release-4.10 so that we can ensure upgrades from 4.10 to 4.11 to 4.12 will work without issue.
> OCPBUGS-2546: UPSTREAM: <carry>: switched policy for PodDisruptionBudget from v1beta1 to v1 in time for 1.25

- cluster-autoscaler/cloudprovider/clusterapi/README.md
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/main.go
- cluster-autoscaler/utils/cpu/architecture.go
- cluster-autoscaler/utils/cpu/architecture_test.go
This is a cherry-pick of the upstream PR 6066 (yet to be merged) and is depended on by https://github.com/openshift/cluster-autoscaler-operator/pull/284 to complete the fix.
The architecture label in the build generic labels method of the Cluster API provider is now populated using the cpu.GetDefaultScaleFromZeroArchitecture().Name() method.
The method allows users deploying the cluster-autoscaler to define the default architecture to be used by the cluster-autoscaler for scale up from zero via the --scale-up-from-zero-default-arch flag. Amd64 is kept as a fallback for historical reasons and to maintain compatibility with current providers.
The `SystemArchitecture` type and the functions for parsing architecture names are copied over from the GCE implementation, to be generic across all …
> OCPBUGS-18137: UPSTREAM: 6066: Allow overriding the kubernetes.io/arch label set by the scale from zero methods via a new cmdline arg

- OWNERS
Since some VPA-only PRs touch files in the root directory, this will make the pod autoscaling team more independent
> PODAUTO-91: Add joelsmith to OWNERS for approving of VPA-only PRs

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
When you use the unstructured utils to fetch a slice, it returns `[]interface{}`, which in fact, is a slice of `map[string]interface{}`. Using a type assertion on the unstructured entries in the slice doesn't work, and will never pass. To actually parse the taint, we have to do our own conversion manually. I've added a small helper that will achieve this and a test that will prevent us from regressing on this.
> OCPBUGS-27509: Fix unstructured taint parsing in Cluster API provider

- vertical-pod-autoscaler/OWNERS
Adds pod autoscaling team member @jkyros to VPA owners
It looks like we haven't touched the owners file since https://github.com/openshift/kubernetes-autoscaler/pull/250
From a "best practices" standpoint: 
- should I retitle this commit to match the commit from #250 (https://github.com/openshift/kubernetes-autoscaler/pull/250/commits/1a5c35650399a5fd8555c81a3b4c49345f007e6f) so it's obvious they could be squashed together next time we do a rebase, or is this okay?
> PODAUTO-104: Add downstream pod autoscaling team member jkyros to VPA OWNERS

- .snyk
This change expands the snyk configuration file to cover more vendor folders and the cloud provider folders which are causing issues. It is safe to exclude other cloud providers because only the clusterapi provider is compiled into the binary for release.
> OCPBUGS-28334: update snyk file

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
This change adds an extra check to ensure that the `value` field is not nil.
> OCPBUGS-31421: add check for taint.value == nil

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
This is a manual cherry-pick of https://github.com/openshift/kubernetes-autoscaler/pull/289
> [release-4.12] OCPBUGS-30911: Fix unstructured taint parsing in Cluster API provider

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_provider_test.go
Avoid expesive pointer copy in capi nodegroup
https://github.com/kubernetes/autoscaler/pull/6796
Fixes #
```release-note
```
```docs
```
> NO-JIRA: UPSTREAM: 6796: Avoid expesive pointer copy in capi nodegroup

- cluster-autoscaler/cloudprovider/cloud_provider.go
- cluster-autoscaler/core/scaleup/orchestrator/orchestrator.go
- cluster-autoscaler/core/static_autoscaler.go
this is a carry port from upstream until we can bring this in the next rebase from upstream.
original description:
> Properly handle calls to NodeGroup.GetOptions() that return cloudprovider.ErrNotImplemented in the scale up path.
> OCPBUGS-33592: fix: scale up broken for providers not implementing NodeGroup.GetOptions()

- vertical-pod-autoscaler/common/version.go
- vertical-pod-autoscaler/deploy/admission-controller-deployment.yaml
- vertical-pod-autoscaler/deploy/recommender-deployment-high.yaml
- vertical-pod-autoscaler/deploy/recommender-deployment-low.yaml
- vertical-pod-autoscaler/deploy/recommender-deployment.yaml
- vertical-pod-autoscaler/deploy/updater-deployment.yaml
- vertical-pod-autoscaler/hack/vpa-process-yaml.sh
- vertical-pod-autoscaler/pkg/updater/priority/scaling_direction_pod_eviction_admission.go
- vertical-pod-autoscaler/pkg/updater/priority/scaling_direction_pod_eviction_admission_test.go
These steps were followed in these commits:
```
git merge-base kubernetes/master vertical-pod-autoscaler-1.1.2
git log --oneline 151923f..vertical-pod-autoscaler-1.1.2  | grep -v Merge.pull
```
The first one is to find the common ancestor, and the next one to show what has changed from that point to the 1.1.2 release (ignoring merge commits)
Then we cherry-pick VPA related commits:
```
for commit in 7d2bd3037 0bc73b3fb 991308df3 cd673e325 b4ce36e40 3609234c5; do
git cherry-pick $commit || break
git commit --amend -m "UPSTREAM: <drop>: $(git show --format=format:%s -s $commit)"
done
```
> PODAUTO-199: Upstream rebase to VPA 1.1.2

- vertical-pod-autoscaler/Dockerfile.openshift
- vertical-pod-autoscaler/Dockerfile.rhel
Change updates VPA images to be consistent with other PodAutoscaling images.
> PODAUTO-202: Update VPA ocp/builder Dockerfile images to openshift/release images

- cluster-autoscaler/main.go
- cluster-autoscaler/metrics/metrics.go
Carry https://github.com/kubernetes/autoscaler/pull/7449 
- Set initial count to zero for various autoscaler error types (e.g., CloudProviderError, ApiCallError)
- Define failed scale-up reasons and initialize metrics (e.g., CloudProviderError, APIError)
- Initialize pod eviction result counters for success and failure cases
- Initialize skipped scale events for CPU and memory resource limits in both scale-up and scale-down directions
> OCPBUGS-25852: UPSTREAM: <carry>: 🐛(metrics) Initialize metrics for autoscaler errors, scale events, and pod evictions

- vertical-pod-autoscaler/Dockerfile.openshift
Just updates the `vertical-pod-autoscaler/Dockerfile.openshift` file to `go1.23/ocp4.19` that is used by CI.
> PODAUTO-266: Update VPA dockerfile to 4.19

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/main.go
- cluster-autoscaler/metrics/metrics.go
cherry-pick of https://github.com/openshift/kubernetes-autoscaler/pull/332
> [release-4.17] OCPBUGS-48606: UPSTREAM: <carry>: 🐛(metrics) Initialize metrics for autoscaler errors, scale events, and pod evictions

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_utils_test.go
Hello! This is a PR to update the autoscaler to recognize both the upstream and openshift ScaleFromZero annotations, while favouring the upstream annotations if they exist. Thanks!
```release-note
```
```docs
```
> OCPCLOUD-2500: Update to recognize both upstream and openshift ScaleFromZero annotations

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
this change ensures that when DecreaseTargetSize is counting the nodes that it does not include any instances which are considered to be pending (i.e. not having a node ref) or are failed. this change will allow the core autoscaler to then decrease the size of the node group accordingly, instead of raising an error.
this commit can be removed once the upstream is in place.
> OCPBUGS-11115: make DecreaseTargetSize more accurate

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
This change makes it so that when a failed machine is found during the `findScalableResourceProviderIDs` it will always gain a normalized provider ID with failure guard prepended. This is to ensure that machines which have gained a provider ID from the infrastructure and then later go into a failed state can be properly removed by the autoscaler when it wants to correct the size of a node group.
> OCPBUGS-11115: improve failed machine detection in clusterapi

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
this change bring in the upstream kubernetes/autoscaler#7952 and kubernetes/autoscaler#7977
> OCPBUGS-11115: refactor findScalableResourceProviderIDs

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
Add improved error handling for machines phase in the ClusterAPI node group implementation. When a machine is in Deleting/Failed/Pending phase, mark the cloudprovider.Instance with a status for cluster-autoscaler recovery actions.
The changes:
- Enhance Nodes listing to allow reporting the machine phase in Instance status
- Add error status reporting for failed machines
This change helps identify and manage failed machines more effectively, allowing the autoscaler to make better scaling decisions.
> NO-JIRA: improve nodes listing in ClusterAPI provider

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
this is a backport of #278,  #343, #347, and #349 combined into a single PR to make things easier.
> [release-4.18] OCPBUGS-53241: improve replica counting and decrease target size behavior

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
this is a backport of #278, #343, #347, and #349 combined into a single PR to make things easier.
> [release-4.17] OCPBUGS-54325: improve replica counting and decrease target size behavior

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_nodegroup_test.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
this is a backport of #278, #343, #347, and #349 combined into a single PR to make things easier.
> [release-4.16] OCPBUGS-54326:  improve replica counting and decrease target size behavior

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
this change reverts the fix from PR 278 that attempted to make the replica counting more accurate for openshift. It is being reverted due to a failure in our test verification that gave a false positive on improving the counting.
this commit, and the related commit from PR 278 should be dropped on the next kubernetes rebase.
> [release-4.19] OCPBUGS-60900: revert openshift replica fix

- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_controller.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured.go
- cluster-autoscaler/cloudprovider/clusterapi/clusterapi_unstructured_test.go
this change reverts the fix from PR 278 that attempted to make the replica counting more accurate for openshift. It is being reverted due to a failure in our test verification that gave a false positive on improving the counting.
this commit, and the related commit from PR 278 should be dropped on the next kubernetes rebase.
> [release-4.16] OCPBUGS-60915: revert openshift replica fix
